services:
  php:
    image: tugboatqa/php:7.2-apache
    default: true
    depends: mariadb
    commands:
      init:
        # Add in extra PHP settings. Note the file renaming.
        # - cp "${TUGBOAT_ROOT}/.tugboat/php.ini"  /usr/local/etc/php/conf.d/backdrop-php.ini
        # Install prerequisite packages.
        # - apt-get update
        # - apt-get install -y mysql-client
        # - docker-php-ext-install opcache zip
        # - a2enmod rewrite expires headers
        # Link the document root to the expected path.
        - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
      update:
        # Use the Tugboat-specific Backdrop settings.
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/settings.local.php"
        # Generate a unique hash_salt to secure the site.
        - echo "\$settings['hash_salt'] = '$(openssl rand -hex 32)';" >> "${DOCROOT}/settings.local.php"
        # Create and set the config directory.
        - mkdir "${DOCROOT}/files/config_$TUGBOAT_PREVIEW_ID"
        - mkdir "${DOCROOT}/files/config_$TUGBOAT_PREVIEW_ID/active"
        - mkdir "${DOCROOT}/files/config_$TUGBOAT_PREVIEW_ID/staging"
        - echo "\$config_directories['active'] = 'files/config_$TUGBOAT_PREVIEW_ID/active';" >> "${DOCROOT}/settings.local.php"
        - echo "\$config_directories['staging'] = 'files/config_$TUGBOAT_PREVIEW_ID/staging';" >> "${DOCROOT}/settings.local.php"
        # Set appropriate file permissions/ownership.
        - chown -R www-data:www-data "${TUGBOAT_ROOT}"
        - find "${DOCROOT}" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}" -type f -exec chmod 0664 {} \;
        # Install Backdrop.
        - cd ${DOCROOT} && ./core/scripts/install.sh --db-url=mysql://tugboat:tugboat@mariadb/tugboat --account-pass=password
      build:
        # - cd ${DOCROOT} && ./.tugboat/auto-login.sh
  mariadb:
    image: tugboatqa/mariadb:latest
    commands:
      init:
        # Configure database for UTF8-MB4: https://api.backdropcms.org/database-configuration
        # - printf "[mysqld]\ninnodb_large_prefix=true\ninnodb_file_format=barracuda\ninnodb_file_per_table=true\n" >> /etc/mysql/conf.d/utf8mb.conf
        # - mysql -e "CREATE DATABASE backdrop; GRANT ALL PRIVILEGES ON backdrop.* TO 'tugboat'@'%';"
